name: "personal"
description: "Personal development environment with all tools and features"

# Environment Type
environment_type: "personal"

# Packages and Applications
packages:
  cli_tools:
    essential: true
    additional: ["tldr", "jq"]
    
  development_tools:
    essential: true
    additional: ["rust", "go"]
    
  productivity:
    essential: true
    additional: []
    
  browsers:
    essential: true
    additional: []
    
  communication:
    essential: true
    additional: []
    
  media:
    essential: true
    additional: []
    
  utilities:
    essential: true
    additional: []
    
  creative:
    essential: true
    additional: []
    
  gaming:
    essential: true
    additional: []

# AI Tool Configurations
ai_tools:
  # Goose Configuration
  goose:
    enabled: true
    default_provider: "anthropic"
    default_model: "claude-3-5-sonnet-latest"
    extensions:
      - name: "developer"
        enabled: true
      - name: "computercontroller"
        enabled: true
      - name: "memory"
        enabled: true
      - name: "time"
        enabled: true
      - name: "repomix"
        enabled: true
      - name: "mcp-server-git"
        enabled: true
      - name: "mcp-server-fetch"
        enabled: true
      - name: "mcp-server-puppeteer"
        enabled: true
      - name: "tutorial"
        enabled: false
      - name: "mcp-installer"
        enabled: false
        
  # Aider Configuration
  aider:
    enabled: true
    default_model: "claude-3-sonnet-20240229"
    models:
      - alias: "fast"
        model: "gpt-4o-mini"
      - alias: "smart"
        model: "gpt-4o"
      - alias: "opus"
        model: "claude-3-opus-20240229"
      - alias: "sonnet"
        model: "claude-3-sonnet-20240229"
    settings:
      editor: "cursor --wait"
      
  # ADW Configuration
  adw:
    enabled: true
    default_workflow: "basic"
    workflows:
      - name: "basic"
        coder_model: "claude-3-sonnet-20240229"
        evaluator_model: "gpt-4o"
        max_iterations: 3
      - name: "complex"
        coder_model: "claude-3-opus-20240229"
        evaluator_model: "gpt-4o"
        max_iterations: 5
        
# Custom shell settings
shell:
  aliases:
    - name: "ai-code"
      command: "aider --model claude-3-sonnet-20240229"
    - name: "ai-explain"
      command: "aider --model gpt-4o-mini --no-git"
    - name: "ai-context"
      command: "run-repomix xml"
    - name: "ai-workflow"
      command: "python ~/Projects/dotfiles/bin/run_adw.py" 