name: "work"
description: "Work-focused development environment with appropriate tools and settings"

# Environment Type
environment_type: "work"

# Packages and Applications
packages:
  cli_tools:
    essential: true
    additional: ["awscli", "terraform", "kubernetes-cli"]
    
  development_tools:
    essential: true
    additional: ["kubectx", "helm", "gradle"]
    
  productivity:
    essential: true
    additional: ["notion"]
    
  browsers:
    essential: true
    additional: []
    
  communication:
    essential: true
    additional: ["microsoft-teams"]
    
  media:
    essential: false
    additional: []
    
  utilities:
    essential: true
    additional: ["rectangle-pro"]
    
  creative:
    essential: false
    additional: []
    
  gaming:
    essential: false
    additional: []

# AI Tool Configurations
ai_tools:
  # Goose Configuration
  goose:
    enabled: true
    default_provider: "anthropic"
    default_model: "claude-3-opus-20240229"
    extensions:
      - name: "developer"
        enabled: true
      - name: "computercontroller"
        enabled: true
      - name: "memory"
        enabled: true
      - name: "time"
        enabled: true
      - name: "repomix"
        enabled: true
      - name: "mcp-server-git"
        enabled: true
      - name: "mcp-server-fetch"
        enabled: true
      - name: "mcp-server-puppeteer"
        enabled: true
      - name: "tutorial"
        enabled: false
      - name: "mcp-installer"
        enabled: false
        
  # Aider Configuration
  aider:
    enabled: true
    default_model: "claude-3-opus-20240229"
    models:
      - alias: "fast"
        model: "gpt-4o-mini"
      - alias: "smart"
        model: "gpt-4o"
      - alias: "opus"
        model: "claude-3-opus-20240229"
      - alias: "sonnet"
        model: "claude-3-sonnet-20240229"
    settings:
      editor: "code --wait"
      
  # ADW Configuration
  adw:
    enabled: true
    default_workflow: "work"
    workflows:
      - name: "work"
        coder_model: "claude-3-opus-20240229"
        evaluator_model: "gpt-4o"
        max_iterations: 4
        
# Custom shell settings
shell:
  aliases:
    - name: "ai-code"
      command: "aider --model claude-3-opus-20240229"
    - name: "ai-explain"
      command: "aider --model claude-3-sonnet-20240229 --no-git"
    - name: "ai-context"
      command: "run-repomix xml"
    - name: "ai-workflow"
      command: "python ~/Projects/dotfiles/bin/run_adw.py --profile work" 