coder_model: claude-3-sonnet-20240229
context_editable:
- /Users/dylansheffer/Projects/dotfiles/LICENSE
- /Users/dylansheffer/Projects/dotfiles/CHANGELOG.md
- /Users/dylansheffer/Projects/dotfiles/install.sh
- /Users/dylansheffer/Projects/dotfiles/Brewfile.work
- /Users/dylansheffer/Projects/dotfiles/README.md
context_read_only:
- /Users/dylansheffer/Projects/dotfiles/README.md
- /Users/dylansheffer/Projects/dotfiles/contexts/ADW.md
evaluator: default
evaluator_model: gpt-4o
execution_command: echo "Testing workflow..."
log_file: configadwupdate-docsyaml_workflow.log
max_iterations: 3
prompt: ./config/adw/update-docs.yaml
